language: node_js
node_js:
      - "8"
      - "9"
      - "10"
install:
     - npm install
script:
     - npm run test
after_success:
      - npm run test:cov
notifications:
  email:
    - adrien.deperetti.freelance@gmail.com