language: node_js
node_js:
      - "8.9.0"
install:
     - npm install
script:
     - npm run test:cov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
  email:
    - adrien.deperetti@gmail.com